log_level: INFO
user: "13477077180"
password: "9HcFkKMjn5B2TgP"
exe_path: "C:\\ths\\xiadan.exe"
broker: "universal_client"
enable_type_keys_for_editor: true
api_token: "ec31c154fc0cbf4ba39eb48689ebcbfaacf8067f"

